apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: user-deployment
            image: tannguyenit/bsm-user-service
            command: ["node", "cronjob.js"]
          restartPolicy: Never