apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccountName: user
      containers:
        - image: tannguyenit/bsm-user-service
          imagePullPolicy: IfNotPresent
          name: user
          resources:
            requests:
              cpu: 200m # The container requests 200 millicores (that is, 1/5 of a single CPU core’s time).
              memory: 10Mi # The container also requests 10 mebibytes of memory.
            limits:
              memory: "512Mi"
              cpu: 10Mi
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          securityContext:
            privileged: false
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: microservice-cm